### ISSUE TITLE
Resistors R1, R2 and R3

### ISSUE THREAD

**Issue by pski** [apuder/TRS-IO#13]
I just noticed there are 3 new resistors on the TRS-IO board, R1, R2 and R3.  What are the specs for these?

**Comment by apuder** [comment]
I was a little lazy with the design of the RSC and didn't include any resistor for the multi-color LED. The 3.3V don't kill the LED. For TRS-IO @jaquinn added resistors for the RGB pins. Some small value (e.g., 100 Ohms) should be fine.
