### ISSUE TITLE
rsclient.c missing?

### ISSUE THREAD

**Issue by johnwiggins** [apuder/TRS-IO#14]
Building the esp code results in missing symbols in trs-io.elf:
CXX build/retrostore/retrostore.o
AR build/retrostore/libretrostore.a
LD build/trs-io.elf
build/retrostore/libretrostore.a(retrostore.o):(.literal._ZN16RetroStoreModule7sendCMDEv[RetroStoreModule::sendCMD()]+0x0): undefined reference to `rsclient_cmd'
build/retrostore/libretrostore.a(retrostore.o):(.literal._ZN16RetroStoreModule7sendCMDEv[RetroStoreModule::sendCMD()]+0x8): undefined reference to `rsclient_cmd_len'

Source of retrostore.cpp refers to those symbols being defined in rsclient.c, which is not in the repo.

This is driving me nuts because the ESP binaries in the repo look like they're actually retrostore card binaries, not those shown in the README. 

Thanks!

**Comment by apuder** [comment]
rsclient.c is created by the Makefile in ~/src/trs. Call the top-level Makefile to make sure everything is compiled in the correct order.
