### ISSUE TITLE
Building ESP Firmware

### ISSUE THREAD

**Issue by iceblu3710** [apuder/TRS-IO#17]
I am having nothing but a horrible time getting the esp_ift tools to actually compile this project correctly. Mostly they are due to esp_idf errors itself.

With a project like this is there a binary release or a stable release pre-compiled that I can simply write to the PLD and ESP32?

**Comment by apuder** [comment]
My apologies for the troubles you are having. I should write up some documentation on how to build the firmware. One thing to note (that is not documented anywhere): you need to use version 3.2.2 of the Espressif SDK. The latest version of the SDK does not compile TRS-IO. You also need to run "make" in the /src directory as this will generate some files that are needed for the ESP firmware. Feel free to post additional issues.
