### ISSUE TITLE
Model I long button press triggered

### ISSUE THREAD

**Issue by vodkaflip** [apuder/TRS-IO#27]
On the model I version, is_button_long_press seems to be continuously triggered. This results in the ESP32 erasing the stored credentials and resetting continuously. If I comment out that piece of code (in /src/esp/main/io.cpp), the TRS-IO works as it should.

**Comment by apuder** [comment]
I have noticed that as well. There seems to be an issue with the latest stable version of the ESP-IDF v3 branch. Please use v3.2.2 of the ESP-IDF as well as the toolchain. That works for me without any modification of io.cpp.
