### ISSUE TITLE
SD card not working

### ISSUE THREAD

**Issue by troffon** [apuder/TRS-IO#34]
The SD card status on the TRS-IO Configuration page shows up red, when I hover the mouse over it says "Failed to initialize SD card".
I've tried a couple of SD cards, both Class 4 formatted as FAT32.

Checked connections of SD card holder to PCB.

WiFi/SMB share works fine.

**Comment by apuder** [comment]
Can you post the ESP'S log? (idf.py monitor)

**Comment by troffon** [comment]
Unfortunately I'm not familiar with the idf tools.
Attached a log which I got by connecting Putty to ESP32 serial port, hope this will be of use.
Thanks
[ESP32_Putty.log](https://github.com/apuder/TRS-IO/files/9206992/ESP32_Putty.log)

**Comment by troffon** [comment]
After seeing that the ESP log failed early on sdmmc_card_init, I decided to re-solder all the sd card contacts.
Now the sd card is functioning correctly.
Closing this issue.
