### ISSUE TITLE
SD-Card slot - cannot find available part TFP09-2-12B - is there a cross?

### ISSUE THREAD

**Issue by dhlav** [apuder/TRS-IO#35]
Hello, I've forked this project and noticed the sd card slot is using a part that doesn't seem to be available easily. Is there a cross # for this before I modify the footprint and board?  This is the M1 v2 non-xray. Thanks! Dave.

**Comment by apuder** [comment]
This is the part I am using: https://www.aliexpress.us/item/2251832720637377.html
