### ISSUE TITLE
Details on version history is incomplete.

### ISSUE THREAD

**Issue by FreddyKElmSt** [apuder/TRS-IO#40]
What does each version do differently? 

There are nine versions of the Model III boards, which I am looking to build, as well as many variants of the Model 1 board, Can you please explain the differences?

What source codes work for which version of board?

Which board would you recommend, the 2.2b?  Or a different board?

Does the source code work for the most recent board (2.2b)?

**Comment by apuder** [comment]
We keep older versions in separate directories. In general, you should use the latest version of the PCB. The firmware will work for that version.
